"""
00_corpus_manifest.py  —  Hebrew corpus manifest
=================================================
Defines the training corpus and test targets for the Hebrew diachronic
pipeline, then writes hebrew/corpus_manifest.json.

Register taxonomy
-----------------
SBH          Standard Biblical Hebrew — pre-exilic prophets and narrative
             (~760–600 BCE).  Features: high wayyiqtol, אנכי present, no שׁ,
             high פן/טרם/נא particles, low niphal passivisation.

Transitional Mixed or transitional Hebrew — exilic and early post-exilic
             (~600–450 BCE).  SBH features largely intact but first LBH
             intrusions appear (growing frac_ani, occasional שׁ, rising
             abstract nouns).

LBH          Late Biblical Hebrew — post-exilic corpus.  Features: exclusive
             אני, frequent שׁ, high negative existential אין, high niphal,
             high -ūt abstract nouns, low פן/טרם.

Archaizing   Not a training class — detected post-hoc by mixing incoherence:
             high archaic-style score AND detectable late leakage markers.
             Candidate test texts include Pentateuch sources where the style
             appears archaic but temporal leakage features suggest a later
             compositional stratum.

Training / holdout split
------------------------
Three holdouts are held back from classifier and MVN training, one per
register, to validate the full pipeline end-to-end:

  SBH holdout         : Habakkuk (605 BCE) — small, unambiguously SBH
  Transitional holdout: Haggai   (520 BCE) — short, clear transitional
  LBH holdout         : Daniel   (167 BCE) — Hellenistic, unambiguous LBH

Test targets (no known reliable date — the whole point of the exercise)
------------------------------------------------------------------------
  D_source   — Deuteronomistic source (D) of the Pentateuch
  P_source   — Priestly source (P)
  JE_source  — Yahwist/Elohist source (J+E combined)

These three use pre-computed feature profiles from source_feature_profiles.csv
(generated by 19_torah_source_analysis.py) and do not participate in training.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(HERE, "corpus_manifest.json")

# ---------------------------------------------------------------------------
# Training corpus
# Format: id, date_bce (positive = BCE), date_sigma, register, genre, holdout
# ---------------------------------------------------------------------------
# date_bce  = central estimate (positive means BCE)
# date_sigma = 1-σ uncertainty in years
# register   = 'SBH' | 'Transitional' | 'LBH'
# genre      = 'prophecy' | 'narrative' | 'wisdom' | 'poetry'
# holdout    = True if withheld from training
# ---------------------------------------------------------------------------
TRAINING = [
    # ── SBH (pre-exilic prophets, ~760–605 BCE) ─────────────────────────────
    # These texts are pre-exilic prophetic literature.  Dates follow the
    # scholarly consensus from Hurvitz (1972), Hendel & Joosten (2018).
    dict(id="Amos",        date_bce=760, date_sigma=15,  register="SBH",          genre="prophecy", holdout=False),
    dict(id="Hosea",       date_bce=725, date_sigma=20,  register="SBH",          genre="prophecy", holdout=False),
    dict(id="Micah",       date_bce=720, date_sigma=20,  register="SBH",          genre="prophecy", holdout=False),
    dict(id="Isaiah_1",    date_bce=700, date_sigma=15,  register="SBH",          genre="prophecy", holdout=False),
    dict(id="Zephaniah",   date_bce=630, date_sigma=15,  register="SBH",          genre="prophecy", holdout=False),
    dict(id="Nahum",       date_bce=620, date_sigma=20,  register="SBH",          genre="prophecy", holdout=False),
    dict(id="Habakkuk",    date_bce=605, date_sigma=20,  register="SBH",          genre="prophecy", holdout=True),
    # ── Transitional (exilic and early post-exilic, ~590–450 BCE) ───────────
    # Jeremiah (590 BCE): largely SBH but Deuteronomistic prose sections show
    # LBH intrusion.  The full book is used here as a Transitional anchor.
    # Lamentations, Ezekiel, Deutero-Isaiah: classic transitional profile.
    dict(id="Jeremiah",    date_bce=590, date_sigma=15,  register="Transitional", genre="prophecy", holdout=False),
    dict(id="Lamentations",date_bce=586, date_sigma=20,  register="Transitional", genre="poetry",   holdout=False),
    dict(id="Ezekiel",     date_bce=570, date_sigma=15,  register="Transitional", genre="prophecy", holdout=False),
    dict(id="Isaiah_2",    date_bce=550, date_sigma=20,  register="Transitional", genre="prophecy", holdout=False),
    # Haggai / Zechariah: short post-exilic prophets, still largely SBH-style
    # but date firmly post-exilic → classic Transitional evidence.
    dict(id="Haggai",      date_bce=520, date_sigma=5,   register="Transitional", genre="prophecy", holdout=True),
    dict(id="Zechariah_1", date_bce=518, date_sigma=5,   register="Transitional", genre="prophecy", holdout=False),
    # Trito-Isaiah: later than Deutero-Isaiah; broad sigma reflects contested
    # compositional history (late 6th–4th c. BCE).
    dict(id="Isaiah_3",    date_bce=500, date_sigma=100, register="Transitional", genre="prophecy", holdout=False),
    dict(id="Malachi",     date_bce=460, date_sigma=20,  register="Transitional", genre="prophecy", holdout=False),
    # ── LBH (post-exilic, ~400–165 BCE) ─────────────────────────────────────
    # Jonah is placed in LBH on linguistic grounds despite narrative setting.
    dict(id="Jonah",       date_bce=400, date_sigma=50,  register="LBH",          genre="narrative", holdout=False),
    # Chronicles, Ezra, Nehemiah: quintessential LBH narrative.
    dict(id="Chronicles",  date_bce=350, date_sigma=30,  register="LBH",          genre="narrative", holdout=False),
    dict(id="Esther",      date_bce=350, date_sigma=50,  register="LBH",          genre="narrative", holdout=False),
    dict(id="Ezra",        date_bce=350, date_sigma=75,  register="LBH",          genre="narrative", holdout=False),
    dict(id="Nehemiah",    date_bce=350, date_sigma=75,  register="LBH",          genre="narrative", holdout=False),
    # Ecclesiastes: extreme LBH/Aramaic-influenced, dated 4th–3rd c. BCE.
    dict(id="Ecclesiastes",date_bce=330, date_sigma=80,  register="LBH",          genre="wisdom",    holdout=False),
    # Daniel: Hellenistic Hebrew portions (chs. 1, 8–12), ~167 BCE Maccabean.
    dict(id="Daniel",      date_bce=167, date_sigma=10,  register="LBH",          genre="mixed",     holdout=True),
]

# ---------------------------------------------------------------------------
# Test targets — no training date, classification and dating are the output
# ---------------------------------------------------------------------------
# Date ranges come from the scholarly literature as priors for the MVN model.
# The pipeline will test whether the morphosyntactic evidence is consistent
# with these priors or flags archaizing mixing incoherence.
#
# Whole-source aggregates (feature profiles from source_feature_profiles.csv):
#   D_source  — Deuteronomy; scholarly range ~7th–6th c. BCE (Josiah-era to
#               exilic editing).  Prior: 625 BCE ± 100 yr.
#   P_source  — Priestly texts in Genesis–Numbers; Hurvitz argues pre-exilic
#               (~700–550 BCE), cross-dating to Ezekiel favours 6th c.
#               Prior: 600 BCE ± 100 yr.
#   JE_source — Yahwist/Elohist narrative; widely placed 9th–8th c. BCE.
#               Prior: 800 BCE ± 75 yr.
#
# Sub-source units (require BHSA sub-source re-extraction to get morpho
# feature vectors; chapter-aggregated n-gram dates available immediately):
#
#   D sub-components (Deuteronomy chapter ranges):
#     D_Code   — Deuteronomic Code, ch. 12–26 (legal core)
#                Prior: 625 BCE ± 100 yr (same as D_source).
#     D_Frame  — Framing speeches, ch. 1–11 + 27–31 + 33–34 (narrative/paraenetic)
#                Prior: 600 BCE ± 100 yr (possibly later redaction).
#     D_Song   — Song of Moses, ch. 32 (ancient poem; noisy)
#                Prior: 900 BCE ± 200 yr (archaic poem, possibly pre-Deuteronomic).
#
#   P sub-components (Leviticus chapter ranges):
#     Lev_Holiness  — Holiness Code (H), ch. 17–26
#                     Prior: 575 BCE ± 75 yr (H stratum, Knohl/Milgrom).
#     Lev_Priestly  — Core Priestly ritual laws, ch. 1–16
#                     Prior: 600 BCE ± 100 yr.
#
#   JE per-book (chapter ranges, J+E not separated):
#     Gen_JE   — Genesis J+E narrative (ch. 2–50 less P)
#                Prior: 800 BCE ± 100 yr.
#     Exo_JE   — Exodus J+E (ch. 1–24 less P, ~narrative + covenant code)
#                Prior: 800 BCE ± 100 yr.
#     Num_JE   — Numbers J+E (scattered narrative sections)
#                Prior: 800 BCE ± 100 yr.
#
# NOTE: Sub-source IDs with suffix "_sub" indicate BHSA features not yet
# extracted; dates come from chapter-aggregated n-gram model only.
# ---------------------------------------------------------------------------
TEST_TARGETS = [
    # Whole-source aggregates (morpho feature profiles available)
    dict(id="D_source",       prior_bce=625, prior_sigma=100,
         description="Deuteronomistic source (D) — whole book"),
    dict(id="P_source",       prior_bce=600, prior_sigma=100,
         description="Priestly source (P) — whole source"),
    dict(id="JE_source",      prior_bce=800, prior_sigma=75,
         description="Yahwist/Elohist source (JE) — whole source"),
    # D sub-components (n-gram dating available; morpho features need BHSA)
    dict(id="D_Code",         prior_bce=625, prior_sigma=100,
         description="Deuteronomic Code (D), ch. 12–26 [needs BHSA morpho]"),
    dict(id="D_Frame",        prior_bce=600, prior_sigma=100,
         description="D framing speeches, ch. 1–11 + 27–34 [needs BHSA morpho]"),
    dict(id="D_Song",         prior_bce=900, prior_sigma=200,
         description="Song of Moses, Deut. 32 — archaic poem [noisy]"),
    # P sub-components (n-gram dating available; morpho features need BHSA)
    dict(id="Lev_Holiness",   prior_bce=575, prior_sigma=75,
         description="Holiness Code (H), Lev. 17–26 [needs BHSA morpho]"),
    dict(id="Lev_Priestly",   prior_bce=600, prior_sigma=100,
         description="Core Priestly laws, Lev. 1–16 [needs BHSA morpho]"),
    # JE per-book sub-units (n-gram dating available; morpho features need BHSA)
    dict(id="Gen_JE",         prior_bce=800, prior_sigma=100,
         description="Genesis JE narrative [needs BHSA morpho]"),
    dict(id="Exo_JE",         prior_bce=800, prior_sigma=100,
         description="Exodus JE narrative [needs BHSA morpho]"),
    dict(id="Num_JE",         prior_bce=800, prior_sigma=100,
         description="Numbers JE narrative [needs BHSA morpho]"),
]


def main():
    manifest = dict(training=TRAINING, test_targets=TEST_TARGETS)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)

    # Summary
    regs = {}
    for e in TRAINING:
        r = e["register"]
        regs.setdefault(r, []).append(e["id"])

    print(f"Wrote {OUT}")
    print()
    print("Training corpus:")
    for reg in ["SBH", "Transitional", "LBH"]:
        ids  = regs.get(reg, [])
        hold = [e["id"] for e in TRAINING if e["register"] == reg and e["holdout"]]
        train= [e["id"] for e in TRAINING if e["register"] == reg and not e["holdout"]]
        date_range = (
            min(e["date_bce"] for e in TRAINING if e["register"] == reg),
            max(e["date_bce"] for e in TRAINING if e["register"] == reg),
        )
        print(f"  {reg:12s}  {len(train):2d} training + {len(hold)} holdout  "
              f"({date_range[0]}–{date_range[1]} BCE)")
        for eid in sorted(ids, key=lambda x: next(e['date_bce'] for e in TRAINING if e['id']==x), reverse=True):
            flag = " [HOLDOUT]" if eid in hold else ""
            date = next(e['date_bce'] for e in TRAINING if e['id']==eid)
            print(f"    {eid:20s}  {date} BCE{flag}")
    print()
    print("Test targets:")
    for t in TEST_TARGETS:
        print(f"  {t['id']:12s}  prior {t['prior_bce']} ± {t['prior_sigma']} BCE  —  {t['description']}")


if __name__ == "__main__":
    main()
