"""Insert the two new figures and remove the two superseded timeline figures."""
import pathlib, re, sys
p = pathlib.Path("main_new.tex"); t = p.read_text()

FIG1 = r"""
\begin{figure}[!ht]
\includegraphics[width=\linewidth]{figures/fig1_ordering.png}
\caption{\textbf{The ordinal signal, under leakage-free cross-validation.}
\textbf{(A)}~Hebrew: scholarly date against leave-one-out predicted date for
all 25 dated units, both model families.  Time runs left to right on both
axes.  The dashed diagonal is perfect prediction and the shaded band is the
conformal 68\% interval.  The vertical strip marks the exilic window, 47~yr
wide against roughly 130~yr of irreducible error and therefore not
resolvable; vertical and horizontal rules mark the 586 and 332~BCE
boundaries.  \textbf{(B)}~Greek: the same analysis on 63 texts spanning
440~BCE--360~CE.  Scatter about the diagonal is proportionally larger
despite the larger corpus.  \textbf{(C)}~Pairwise ordering accuracy against
the permutation null.  Thin bars span the null 2.5--97.5 percentiles, thick
bars the interquartile range, the vertical tick the null mean; filled
markers are observed values.  The null is generated by shuffling the date
labels and re-running the entire pipeline, so it preserves the dependence
among pairs that a binomial test ignores.  All four observed values exceed
chance; none does so by a wide margin.}
\label{fig:ordering}
\end{figure}
"""

FIG2 = r"""
\begin{figure}[!ht]
\includegraphics[width=\linewidth]{figures/fig2_timeline.png}
\caption{\textbf{Dated corpus and undated units on a common timeline.}
\textbf{(A)}~The 25 dated units with scholarly date and stated $\sigma$.
Widened sigmas on literary-critically dated texts (Joel, Zechariah~9--14,
Ecclesiastes, Isaiah~56--66, Obadiah) are visible as long bars.  Open
diamonds mark the two units held out of both models.  \textbf{(B)}~The 19
undated units with conformal 68\% ranges from both model families, ordered
by the generative point estimate.  No range is confined to a single period.
The Song of the Sea and the Song of Deborah are the earliest units under
both families and the only two whose mass sits predominantly before
586~BCE; neither was used in training.  Shaded bands are the conventional
periods, given for orientation only --- the ranges, not the band a range
happens to overlap, are the result.}
\label{fig:timeline}
\end{figure}
"""

# place Fig 1 immediately after the "What the signal supports" subsection
anchor = ("This is the one result\nthat replicates across both families at the level of the primary endpoint,\n"
          "and it is the strongest finding in the paper.")
if anchor not in t: sys.exit("ANCHOR: what-the-signal-supports")
t = t.replace(anchor, anchor + "\n" + FIG1)

# place Fig 2 right after the targets table
anchor2 = r"\label{tab:targets}" + "\n" + r"\end{table}"
if anchor2 not in t: sys.exit("ANCHOR: tab:targets")
t = t.replace(anchor2, anchor2 + "\n" + FIG2)

# drop the two superseded timeline figures
def drop(block_key):
    global t
    m = re.search(r"\\begin\{figure\}(?:(?!\\end\{figure\}).)*?" + re.escape(block_key)
                  + r"(?:(?!\\end\{figure\}).)*?\\end\{figure\}\n?", t, re.S)
    if not m: sys.exit(f"FIGURE BLOCK NOT FOUND: {block_key}")
    t = t[:m.start()] + t[m.end():]
    return True

for k in ("fig1_corpus_timeline.png", "fig_s12_corpus_timeline.png"):
    drop(k); print(f"  dropped {k}")

# repoint references to the removed timeline figure
t = t.replace(r"Fig~\ref{fig:corpus_timeline}", r"Fig~\ref{fig:timeline}")
t = t.replace(r"Figure~\ref{fig:corpus_timeline}", r"Figure~\ref{fig:timeline}")
t = t.replace(r"\ref{fig:corpus_timeline}", r"\ref{fig:timeline}")
t = t.replace(r"S12~Fig", r"Fig~\ref{fig:timeline}")
t = t.replace(r"\nameref{S12_Fig}", r"Fig~\ref{fig:timeline}")

p.write_text(t)
labels = set(re.findall(r"\\label\{([^}]+)\}", t))
refs = set(re.findall(r"\\(?:name)?ref\{([^}]+)\}", t))
print("  dangling:", sorted(refs - labels) or "none")
print("  figures now:", sorted(set(re.findall(r"figures/(\S+?)\.png", t))))

# ── swap in the regenerated S-tables ─────────────────────────────────────────
import pathlib as _pl
t = p.read_text()
END = "\\end{document}"
if END not in t:
    sys.exit("no \\end{document} found - cannot place S-tables")
for old_label, newfile in [("tab:s2_power", "tab_s2_power.tex"),
                           ("tab:s5_words", "tab_s5_words.tex")]:
    if old_label not in t:
        # must go BEFORE \end{document} or LaTeX never sees the label
        i = t.rfind(END)
        t = t[:i] + _pl.Path(newfile).read_text() + "\n" + t[i:]
p.write_text(t)
print("  appended regenerated S2/S5 tables")
