"""
Final patch pass: corrected pairwise p-values and the Greek replication.

The binomial test treats 295 pairs generated by 25 texts as independent.
They are not.  Correct p-values come from the permutation null used
everywhere else in the paper.
"""
import pathlib, sys

p = pathlib.Path("/home/claude/paper/main_new.tex")
t = p.read_text(); n = 0

def rep(old, new, label):
    global t, n
    if old not in t:
        sys.exit(f"ANCHOR NOT FOUND (final): {label}")
    t = t.replace(old, new); n += 1

rep("the models order\ntext pairs chronologically with 69.8\\% accuracy across 295 pairs\n"
    "($p = 4 \\times 10^{-12}$), and leave-one-out Spearman correlations between\n"
    "true and predicted dates are $+0.58$ and $+0.49$ in the two families\n"
    "($p = 0.016$, $0.024$ against a permutation null).",
    "the models order\ntext pairs chronologically with 69.8\\% and 67.8\\% accuracy across 295\n"
    "pairs, against a permutation null of 47.6\\% and 43.6\\% ($p = 0.022$,\n"
    "$0.029$), and leave-one-out Spearman correlations between true and\n"
    "predicted dates are $+0.58$ and $+0.49$ ($p = 0.016$, $0.024$).",
    "abstract")

rep("the models order text pairs chronologically with 69.8\\% accuracy across\n"
    "295 pairs ($p = 4 \\times 10^{-12}$), and rank correlations between true\n"
    "and predicted date reach $+0.58$ and $+0.49$ in two independently\n"
    "specified model families.",
    "the models order text pairs chronologically with 69.8\\% and 67.8\\%\n"
    "accuracy across 295 pairs against a permutation null near 45\\%\n"
    "($p = 0.022$, $0.029$), and rank correlations between true and predicted\n"
    "date reach $+0.58$ and $+0.49$ in two independently specified model\n"
    "families.",
    "introduction")

rep("69.8\\% of 295 pairs for the generative family and 67.8\\% for ridge, against\n"
    "a 50\\% baseline ($p = 4 \\times 10^{-12}$ and $5 \\times 10^{-10}$,\n"
    "binomial).",
    "69.8\\% of 295 pairs for the generative family and 67.8\\% for ridge.  We\n"
    "stress that a binomial test is inappropriate here: the 295 pairs are\n"
    "generated by 25 texts and are strongly dependent, and a naive binomial\n"
    "returns $p \\sim 10^{-12}$, wrong by roughly ten orders of magnitude.\n"
    "Under the permutation null --- shuffling dates and re-running the\n"
    "pipeline, which preserves the dependence structure --- the null means are\n"
    "47.6\\% and 43.6\\% with standard deviations near 16 percentage points,\n"
    "giving $p = 0.022$ and $0.029$ (Fig~\\ref{fig:ordering}C).",
    "validation")

rep("morphosyntactic features order text pairs chronologically at 69.8\\%\n"
    "accuracy across 295 pairs, and leave-one-out rank correlations between true\n"
    "and predicted date reach $+0.58$ and $+0.49$ in two independently\n"
    "specified model families.  These are not large effects, but they are not\n"
    "chance, and they replicate.",
    "morphosyntactic features order text pairs chronologically at 69.8\\% and\n"
    "67.8\\% accuracy against a permutation null near 45\\% ($p = 0.022$,\n"
    "$0.029$), and leave-one-out rank correlations reach $+0.58$ and $+0.49$ in\n"
    "two independently specified model families.  These are not large effects,\n"
    "but they are not chance, and they replicate --- across model families\n"
    "within Hebrew, and across languages.",
    "conclusion")

rep("""\\textbf{Cross-linguistic generalization.}
An Ancient Greek corpus was assembled for this purpose and is described in
the repository.  Its holdout results were obtained under the same
prior-leakage design documented under \\nameref{sec:validation} and are
withdrawn here rather than repaired; corrected, they yield errors near
120~yr and do not support a generalization claim.  Whether the framework
transfers across languages is therefore open, and we flag it as the most
consequential outstanding question rather than as a result.""",
    """\\textbf{Cross-linguistic generalization.}
A 63-text Ancient Greek corpus spanning 440~BCE--360~CE was re-analysed
under the identical protocol (Fig~\\ref{fig:ordering}B,C).  The originally
reported holdout recoveries ``within $\\sim$30~yr'' were produced by the
same prior-leakage design documented under \\nameref{sec:validation} and are
withdrawn.  What replaces them is weaker but genuinely cross-linguistic:
pairwise ordering accuracy of 60.3\\% and 58.9\\% against a permutation null
near 40\\% ($p = 0.037$, $0.050$), with leave-one-out rank correlations of
$+0.36$ and $+0.27$.  The ordinal signal replicates in an unrelated
language at comparable significance, and that is the generalization claim
the data support.

The negative result replicates more sharply still.  Greek leave-one-out
MAE is 294.5~yr (generative) and 205.4~yr (ridge) against 210.9~yr for the
constant predictor: one family is substantially worse than a constant and
the other improves on it by five years ($p = 0.24$).  Corrected holdout
errors are 339.0 and 171.2~yr, against the 8.7~yr originally reported.
That this occurs at $n = 63$ over an 800-year span --- where a small
corpus cannot be blamed --- indicates the limitation is intrinsic to the
approach rather than a consequence of sample size.""",
    "cross-linguistic")

p.write_text(t)
print(f"final pass: applied {n} patches")
assert "10^{-12}$)" not in t and "10^{-10}$," not in t, "stale p-value survived"

# ── align the abstract's opening with the "resolution" framing ───────────────
t = p.read_text()
old = ("""The linguistic dating of ancient texts from internal morphosyntactic
evidence is central to biblical studies and classical philology, but the
field's methods have been challenged as circular: models are validated
against dates that are themselves partly linguistic judgements, and
validation designs frequently supply a text's expected date to the model
that is then asked to recover it.  The present paper reports a
leakage-free reassessment.""")
new = ("""The linguistic dating of ancient texts from internal morphosyntactic
evidence is central to biblical studies and classical philology, but its
resolution --- how finely a text can actually be placed in time --- has
never been measured.  Reported accuracies vary by two orders of magnitude,
in part because validation designs in this area frequently supply a text's
expected date to the model that is then asked to recover it.  The present
paper measures the resolution directly.""")
if old not in t: sys.exit("ANCHOR NOT FOUND (final): abstract opening")
p.write_text(t.replace(old, new))
print("abstract opening realigned to the resolution framing")
