"""
Power analysis for the expanded chunk-level feature space.

The number that governs screening is NOT the chunk count.  Chunks inside a
book share its date and are correlated, so the effective sample size is

    n_eff = n_chunks / DEFF,     DEFF = 1 + (m_bar - 1) * ICC

with m_bar the average chunks per book.  Screening at a nominal alpha using
n_chunks would badly understate the false-discovery cost.  Everything below
is computed against n_eff, and the null is generated by permuting dates at
the BOOK level -- which is the only permutation that respects the design.
"""
import numpy as np, pandas as pd, sys
from scipy import stats

META = {"chunk_id", "unit", "date_bce", "genre", "register", "n_words"}


def load(target):
    D = pd.read_csv(f"/home/claude/big_features_{target}.csv")
    feats = [c for c in D.columns if c not in META]
    X = D[feats].astype(float)
    keep = (X.std() > 0) & (X.isna().mean() < 0.2)
    X = X.loc[:, keep].fillna(X.median())
    return D, X, list(X.columns)


def icc1(x, g):
    df = pd.DataFrame({"x": x, "g": g}).dropna()
    k, n = df.g.nunique(), len(df)
    if k < 3 or n - k <= 0: return np.nan
    grand = df.x.mean()
    gm = df.groupby("g").x.agg(["mean", "count"])
    ssb = (gm["count"] * (gm["mean"] - grand) ** 2).sum()
    ssw = sum(((s.x - s.x.mean()) ** 2).sum() for _, s in df.groupby("g"))
    msb, msw = ssb / (k - 1), ssw / (n - k)
    n0 = (n - (gm["count"] ** 2).sum() / n) / (k - 1)
    d = msb + (n0 - 1) * msw
    return float((msb - msw) / d) if d > 0 else np.nan


def main(target, nperm=400):
    D, X, feats = load(target)
    dates = D.date_bce.values
    units = D.unit.values
    n, p = X.shape
    k = D.unit.nunique()
    mbar = n / k

    iccs = np.array([icc1(X[f].values, units) for f in feats])
    icc_med = np.nanmedian(iccs)
    deff = 1 + (mbar - 1) * max(icc_med, 0)
    n_eff = n / deff

    print("=" * 78)
    print(f"POWER ANALYSIS  |  chunk ~{target}w")
    print("=" * 78)
    print(f"  chunks                       : {n}")
    print(f"  books                        : {k}   (mean {mbar:.1f} chunks/book)")
    print(f"  candidate features           : {p}")
    print(f"  median feature ICC           : {icc_med:.3f}")
    print(f"  design effect  1+(m-1)*ICC   : {deff:.2f}")
    print(f"  EFFECTIVE SAMPLE SIZE        : {n_eff:.1f}")
    print(f"     (book-level analysis had n = {k})")
    print(f"     -> chunking buys a factor of {n_eff/k:.2f} in effective n")

    # observed screening counts vs a book-level permutation null
    obs_p = np.array([stats.spearmanr(X[f].values, dates).pvalue for f in feats])
    rng = np.random.default_rng(11)
    udates = D.groupby("unit").date_bce.first()
    null_counts = {a: [] for a in (0.001, 0.01, 0.05, 0.10)}
    for _ in range(nperm):
        perm = dict(zip(udates.index, rng.permutation(udates.values)))
        dp = np.array([perm[u] for u in units])
        pv = np.array([stats.spearmanr(X[f].values, dp).pvalue for f in feats])
        for a in null_counts:
            null_counts[a].append((pv < a).sum())

    print(f"\n  screening against a BOOK-level permutation null ({nperm} draws)")
    print(f"  {'alpha':>7}{'retained':>10}{'null mean':>11}{'null p95':>10}"
          f"{'est FDP':>9}{'BH q=.10':>10}")
    rows = []
    for a in sorted(null_counts):
        obs = int((obs_p < a).sum())
        nl = np.array(null_counts[a])
        fdp = min(nl.mean() / obs, 1.0) if obs else np.nan
        rows.append((a, obs, nl.mean(), np.percentile(nl, 95), fdp))
        print(f"  {a:7.3f}{obs:10d}{nl.mean():11.1f}{np.percentile(nl,95):10.0f}"
              f"{fdp:9.2f}", end="")
        srt = np.sort(obs_p)
        bh = np.sum(srt <= (np.arange(1, len(srt)+1) / len(srt)) * 0.10)
        print(f"{bh:10d}" if a == 0.001 else "")
    # detectable effect size at n_eff
    print(f"\n  minimum |rho| detectable at 80% power, n_eff = {n_eff:.0f}:")
    for a in (0.001, 0.01, 0.05):
        za, zb = stats.norm.ppf(1 - a / 2), stats.norm.ppf(0.80)
        z = (za + zb) / np.sqrt(max(n_eff - 3, 1))
        print(f"    alpha={a:<6} |rho| >= {np.tanh(z):.2f}")
    print(f"\n  observed |rho| distribution: max {np.max(np.abs([stats.spearmanr(X[f].values,dates).statistic for f in feats])):.2f}")
    return dict(n=n, k=k, p=p, icc=icc_med, deff=deff, n_eff=n_eff)


if __name__ == "__main__":
    res = {}
    for t in (300, 500, 1000):
        res[t] = main(t)
        print()
    print("=" * 78)
    print("SUMMARY: effective n by chunk size")
    print("=" * 78)
    print(f"  {'chunk':>7}{'chunks':>9}{'ICC':>8}{'DEFF':>7}{'n_eff':>8}{'gain vs n=25':>14}")
    for t, r in res.items():
        print(f"  {t:>7}{r['n']:9d}{r['icc']:8.2f}{r['deff']:7.2f}"
              f"{r['n_eff']:8.1f}{r['n_eff']/25:13.2f}x")
